### ISSUE TITLE
Using edgar in Windows environnement

### ISSUE THREAD

**Issue by AdamZ2** [iangow-public/edgar#28]
I am trying to use Ian's code in windows environnement. I have installed postgreSQL but I am getting an error 
at this level : 

> # Push results to database ----
> pg <- dbConnect(PostgreSQL())
Error in postgresqlNewConnection(drv, ...) : 
  RS-DBI driver: (could not connect username@localhost:5432 on dbname "username": FATAL:  role "username" does not exist
)

Any hint ?
Many thanks

**Comment by iangow** [comment]
After installing PostgreSQL, you will need to get the server running and create a database. Unfortunately, I do not know how to these steps on Windows. If you find information on those steps, please put here and I can add to the instructions here. [This tutorial](http://www.postgresqltutorial.com/install-postgresql/) looks helpful.

You should also set up the PostgreSQL-related environment variables discussed [here](https://github.com/iangow-public/wrds_pg#5-environment-variables) (and perhaps also `PGPASSWORD`) so that `dbConnect(PostgreSQL())` works.

**Comment by AdamZ2** [comment]
Many Thanks Ian,I will find the way to do it in Windows.
I have 2 question do you parse the forms after the download?
What are the name of the database that you have created in postgreSQL?
Does the code create the DB which will receive the data?

**Comment by iangow** [comment]
> What are the name of the database that you have created in postgreSQL?

I (for some legacy reason) call *my* database `crsp`. But what you call it should not matter.

> Does the code create the DB which will receive the data?

Which code? Elsewhere I have code that creates a database to receive data, but not here (this code is macOS-specific, I'm afraid). The tutorial above covers this for Windows.

**Comment by AdamZ2** [comment]
Thanks Ian for your help. To save time I will use my Mac with your programm while learning for the windows environnement. Can you plz share the steps that I should do to create the database and make it ready to receive the data?
Also I want to now if your program do some parsing or the data is stored as it is in the DB. Do you know any program that can help extract the numbers from the forms?
Many Thanks
