### ISSUE TITLE
Examine issues with dates

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#36]
Look at this [filing](https://www.sec.gov/Archives/edgar/data/1000623/000100062305000011/xslF345X02/edgar.xml), which has transaction dates.

**Comment by bdcallen** [comment]
@iangow Were you looking at table1 or table2 before? Because table1 for this filing has one row which is a `Holding` so the transaction date should be a null. Wherease table2 has two transactions, both with non-null transaction dates. 

I just did
```r
tbl(pg, sql("SELECT * FROM edgar.forms345_header WHERE file_name = 'edgar/data/1000623/0001000623-05-000011.txt'")) %>% collect()
```
which gave

file_name | document | transaction_or_holding | seq | security_title | transaction_date | deemed_execution_date | transaction_form_type | transaction_code | equity_swap_involved | transaction_timeliness | transaction_shares | transaction_price_per_share | transaction_acquired_disposed_code | shares_owned_following_transaction | value_owned_following_transaction | direct_or_indirect_ownership | nature_of_ownership
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Holding | 1 | SWM Common Stock | NA | NA | NA | NA | NA | NA | NA | NA | NA | 5010 | NA | D | NA

```r
tbl(pg, sql("SELECT * FROM edgar.forms345_table1 WHERE file_name = 'edgar/data/1000623/0001000623-05-000011.txt'")) %>% collect()
```
which gave

file_name | document | transaction_or_holding | seq | security_title | transaction_date | deemed_execution_date | transaction_form_type | transaction_code | equity_swap_involved | transaction_timeliness | transaction_shares | transaction_price_per_share | transaction_acquired_disposed_code | shares_owned_following_transaction | value_owned_following_transaction | direct_or_indirect_ownership | nature_of_ownership
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Holding | 1 | SWM Common Stock | NA | NA | NA | NA | NA | NA | NA | NA | NA | 5010 | NA | D | NA

and 
```r
tbl(pg, sql("SELECT * FROM edgar.forms345_table2 WHERE file_name = 'edgar/data/1000623/0001000623-05-000011.txt'")) %>% collect()
```

file_name | document | transaction_or_holding | seq | security_title | conversion_or_exercise_price | transaction_date | deemed_execution_date | transaction_form_type | transaction_code | ... | transaction_acquired_disposed_code | exercise_date | expiration_date | underlying_security_title | underlying_security_shares | underlying_security_value | shares_owned_following_transaction | value_owned_following_transaction | direct_or_indirect_ownership | nature_of_ownership
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Transaction | 1 | Phantom Stock Units | 0 | 2004-12-31 | NA | 4 | A | ... | A | 1988-08-08 | 1988-08-08 | Common Stock | 22.6800 | NA | 5158.945 | NA | D | NA
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Transaction | 2 | Phantom Stock Units | 0 | 2005-01-03 | NA | 4 | A | ... | A | 1988-08-08 | 1988-08-08 | Common Stock | 198.7047 | NA | 5357.650 | NA | D | NA

Also, I tested my functions on this filing for header, table1 and table2,

```r
get_header(xml_root, file_name, document)
```
which gives 

file_name | document | schema_version | document_type | period_of_report | date_of_original_submission | no_securities_owned | not_subject_to_section16 | form3_holdings_reported | form4_transactions_reported | ... | rpt_owner_good_address | is_director | is_officer | is_ten_percent_owner | is_other | officer_title | other_text | remarks | signature_name | signature_date
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | X0202 | 4 | 2004-12-31 | NA | NA | NA | NA | NA | ... | NA | TRUE | FALSE | FALSE | FALSE | NA | NA | NA | Honor Winks as Attorney-in-Fact for Leonard J. Kujawa | 2005-01-04

```r
get_nonDerivative_df(xml_root, file_name, document, form_type)
```
which gives

file_name | document | form_type | transaction_or_holding | seq | security_title | transaction_date | deemed_execution_date | transaction_form_type | transaction_code | equity_swap_involved | transaction_timeliness | transaction_shares | transaction_price_per_share | transaction_acquired_disposed_code | shares_owned_following_transaction | value_owned_following_transaction | direct_or_indirect_ownership | nature_of_ownership
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | 4 | Holding | 1 | SWM Common Stock | NA | NA | NA | NA | NA | NA | NA | NA | NA | 5010 | NA | D | NA

and 
```r
get_derivative_df(xml_root, file_name, document, form_type)
```
which gives

file_name | document | transaction_or_holding | seq | security_title | conversion_or_exercise_price | transaction_date | deemed_execution_date | transaction_form_type | transaction_code | ... | transaction_acquired_disposed_code | exercise_date | expiration_date | underlying_security_title | underlying_security_shares | underlying_security_value | shares_owned_following_transaction | value_owned_following_transaction | direct_or_indirect_ownership | nature_of_ownership
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Transaction | 1 | Phantom Stock Units | 0 | 2004-12-31 | NA | 4 | A | ... | A | 1988-08-08 | 1988-08-08 | Common Stock | 22.6800 | NA | 5158.945 | NA | D | NA
edgar/data/1000623/0001000623-05-000011.txt | edgar.xml | Transaction | 2 | Phantom Stock Units | 0 | 2005-01-03 | NA | 4 | A | ... | A | 1988-08-08 | 1988-08-08 | Common Stock | 198.7047 | NA | 5357.650 | NA | D | NA

**Comment by iangow** [comment]
Must’ve been Tables  1.
