### ISSUE TITLE
Update edgar.filings

### ISSUE THREAD

**Issue by jingyujzhang** [iangow-public/edgar#7]
The discussion is [here](https://github.com/azakolyukina/misc/issues/6#event-1491052793).

**Comment by jingyujzhang** [comment]
Permission has been fixed.

**Comment by iangow** [comment]
Table should be updated. I will explain how.

**Comment by iangow** [comment]
The code is [here](https://github.com/iangow-public/edgar/blob/master/get_filings.R).

There are two ways to do the update:

1. *Run the whole script.* This will take longer, but is easiest from a coding point of view.
2. *Do an incremental update.* First, work out which quarter is the latest on `edgar.filings`. Second, update that quarter and subsequent quarters by running the code in the first chunk (to set up the function) and then editing the code in the second section accordingly.

Ideally, you would create a script to do an incremental update. One approach would be to move the top chunk to a separate file, then create two files that `source` that code; one for each of the two ways above. The incremental update script would work out what quarters need to be updated (using the current date and the table data) and then update them.

**Comment by jingyujzhang** [comment]
I need permission to do `ALTER, GRANT SELECT, DELETE` on schema `edgar`.

**Comment by iangow** [comment]
OK. You should have that now.

Something like the code below should go in a "clean-up" script. @jingyujzhang Perhaps create an issue related to this on Nastia's `misc` repository.

```
192-168-1-7:~ igow$ psql -h aaz.chicagobooth.edu -d postgres
psql (9.6.5, server 9.4.12)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# GRANT edgar TO jingyuzhang ;
NOTICE:  role "jingyuzhang" is already a member of role "edgar"
GRANT ROLE
postgres=# GRANT ALL ON SCHEMA edgar TO edgar;
GRANT
postgres=# ALTER SCHEMA edgar OWNER TO edgar;
ALTER SCHEMA
postgres=# 
```

**Comment by iangow** [comment]
@jingyujzhang (@azakolyukina):

@bdcallen (works with me in Melbourne) and I re-did this code (see #9). So now one just needs to run `get_filings.R`. This code will determine which, if any, index files have been modified since they were last imported and grab those. The code should work even without data in `edgar.filings`.

(Data on `aaz.chicagobooth.edu` have been updated. But if you run the code after, say, Monday, there should be new filings and the code should cause an update for the current quarter.)

There are lots of other tables in my version of `edgar` (e.g., CUSIP-CIK matches, URLs for all documents, extracting comment letters). @bdcallen will continue to clean these up and document as we work on getting the `edgar` repository into decent shape.

**Comment by jingyujzhang** [comment]
What's the ideal frequency of updating `edgar.filings`?

**Comment by iangow** [comment]
Use the latest code, as there's an [update script](https://github.com/iangow-public/edgar/blob/master/update_edgar.sh) there now. I think weekly or monthly might be good, as it is easy to do and the more often it is done, the smaller the update.

Note that environment variables such as `PGHOST`, `PGDATABASE` (and perhaps `PGUSER` and `PGPASSWORD`) will need to be set before running the script (e.g., in Unix, `export PGDATABASE="crsp"; export PGHOST="aaz.chicagobooth.edu"` or, in R, `Sys.setenv(PGHOST = "aaz.chicagobooth.edu", PGDATABASE = "postgres")`). On `iangow.me`, I have the set in my `~/.profile`, so no extra step is needed.

I dumped the contents of `edgar.filing_docs` from my server to Nastia's using this line:

```
pg_dump -h iangow.me -d crsp --format custom --table edgar.filing_docs | \
    pg_restore -d postgres -h aaz.chicagobooth.edu
```

Updating this table takes time, so I figured it was best to dump this rather than running it all again.

**Comment by iangow** [comment]
The update script gives a few bonus tables (e.g., item numbers from 8-K filings and information on the component documents of filings, which would've been useful [here](https://github.com/azakolyukina/bs_linguistics/tree/master/corpus_10_k) ... see my comment at the top of the `readme`).
